services:
  deployer:
    build: .
    container_name: github-webhook-deployer
    ports:
      - "2026:4000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home:/home
      - /home/kikchan/.ssh:/root/.ssh:ro
    env_file:
      - .env